### ISSUE TITLE
Wrye Bash Unrunable Through Mod Organizer

### ISSUE THREAD

**Issue by AJAdair110** [ModOrganizer2/modorganizer#769]
## The problem:
I just updated to 2.2.0 of Mod Organizer. Now when I go to run Wrye Bash as an executable through MO, it comes up with the following "Folder In Use" warning message: "The action can't be completed because the folder or a file in it is open in another program

Close the folder or file and try again.
(Folder) WryeBash_n5pfyi"

## To Reproduce:

1. Download Wrye Bash and configure it through the configure executables options.
2. Pick Wrye Bash through the drop down menu of programs to run.
3. Click Run
4. Warning Message pops up

## Environment:

* Mod Organizer Version that exhibits the issue: 2.2.0
* Last Mod Organizer Version that did not exhibit the issue (if applicable): Wrye Bash 307 Beta 3
* Desktop OS/version used to run Mod Organizer: Windows 10

## Details:
Wrye Bash does still run outside of Mod Organizer. So somehow MO is making Wrye Bash think it is using a folder it needs.

### USVFS:
https://gist.github.com/AJAdair110/c059bc175ef1fc8971433fd0151d1879

### MO Interface:
https://gist.github.com/AJAdair110/4fcca37efe453e1dbd3fc5db1f2874ea

**Comment by AJAdair110** [comment]
I checked out the latest Dev Build and it is still having this problem with a slightly different folder I cannot locate on my hard drive.

**Comment by isanae** [comment]
I released a new set of DLLs on 18 June that might fix this. Did you try those?

**Comment by Rexmont1** [comment]
I have this same issue with wyre bash.

**Comment by AJAdair110** [comment]
No. Those do not fix the problem. Nor does the new Alpha build.

**Comment by Al12rs** [comment]
Could you provide us with the debug logs of you reproducing the issue on the newest build a available on discord? Use `!get debuglog` in #bot-use for the debuglog instructions.

**Comment by AJAdair110** [comment]
If I did it correctly, this should be the GIST of my debug log: https://gist.github.com/AJAdair110/ca4c1da25ba9552dc4b2527a6f8dc398

**Comment by Rexmont1** [comment]
My problem was fixed between Wyre Bash and MO2 after I updated Windows 10 to Version 1903.

**Comment by AJAdair110** [comment]
I'm updated to the latest version of Windows, and it still isn't working for me.

**Comment by Al12rs** [comment]
Check with vinwer to see the build number. You most likely aren't. Btw we fixed the problem in the dev-builds available on discord, so if you want you could grab one of those instead. https://discord.gg/6GKR9jZ

**Comment by AJAdair110** [comment]
I **have** the latest version of windows **_and_** the latest Dev version of MO from the discord. It's still broken. Also, I assume you mean "winver" and not "vinwer"...

**Comment by AJAdair110** [comment]
Getting the latest version of Windows 10 did fix this. I didn't realize that Windows Automatic Update didn't do feature updates, so I fixed this by doing so manually. Thanks for all your help!
